In [3]:
import numpy as np

In [1]:
x = [2, 3, 4, 5, 6]
y = [a + 2 for a in x]
print(y)

[4, 5, 6, 7, 8]


In [6]:
nums = np.array([2, 3, 4, 5, 6])
nums2 = nums + 2
print(nums2)

[4 5 6 7 8]


In [7]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
type(a)

numpy.ndarray

In [11]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [13]:
zeros = np.zeros((5, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [17]:
ones = np.ones((5, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
lin = np.linspace(1, 10, 10)
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
lin = np.linspace(1, 10, 20)
lin

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### THE RANDOM METHOD

In [21]:
#random values in a given shape
random = np.random.rand(2, 3)
random

array([[0.96546258, 0.76817045, 0.59200125],
       [0.94913035, 0.66890044, 0.24647022]])

In [23]:
# Return a sample (or samples) from the "standard normal" distribution

random = np.random.randn(2, 3)
random

array([[ 1.21904651,  0.56214176, -0.75932586],
       [ 2.82361357, -2.65253648, -1.57442044]])

In [24]:
#Return random integers
random = np.random.randint(50, 100, 5)
random

array([84, 51, 97, 97, 96])

### RESHAPE METHOD

In [25]:
nums = np.arange(1, 17)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
nums2 = nums.reshape(4, 4)
nums2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### MAX/MIN VALUES

In [27]:
random = np.random.randint(1, 100, 5)
print(random)

[29  9 15 74 74]


In [28]:
xmin = random.min()
print(xmin)

9


In [30]:
xmax = random.max()
print(xmax)

74
